DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
	email varchar(255) PRIMARY KEY,
	senha varchar(2048),
	salt varchar(1024),
	certificado varchar(10000),
	attempts INTEGER,
	timeout TIMESTAMP,
	gid INTEGER,
	FOREIGN  KEY (gid)
	    REFERENCES GRUPOS(gid)
);

DROP TABLE IF EXISTS GRUPOS;
CREATE TABLE GRUPOS (
	gid INTEGER PRIMARY KEY
);

DROP TABLE IF EXISTS MENSAGENS;
CREATE TABLE MENSAGENS (
	codigo INTEGER PRIMARY KEY,
	mensagem varchar(2048)
);

DROP TABLE IF EXISTS REGISTROS;
CREATE TABLE REGISTROS (
	timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	usuario  varchar(255),
	codigo INTEGER,
	FOREIGN KEY (usuario)
		REFERENCES USUARIO (email),
	FOREIGN KEY (codigo)
		REFERENCES MENSAGENS (codigo),
	PRIMARY KEY(timestamp, usuario)
);
